### PR TITLE
Regenerate fixtures and exclude Libraries

### PR DESCRIPTION
**Pull request by friederbluemle**
The update to RN 0.60.5 brought in a **ton** of changes to the generated files.

This PR also removes the `Libraries` folders from fixtures.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Good idea @belemaire - Should we try to ignore `system-tests/**/Libraries` as part of this PR (before merging it)? Any other changes that are required when we do that?

**Comment by friederbluemle** [comment]
```
system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/Libraries
system-tests/fixtures/ios-container/ElectrodeContainer/Libraries
```
These two folders together contain more than 2000 files and more than 160.000 lines of code - Removing them from source control would be great! @belemaire - How would this impact CI etc.? Would it increase build/test time? Any build scripts that need to be updated to regenerate these folders every time?

**Comment by belemaire** [comment]
@friederbluemle 
Yes sounds good. Could you just `git rm` everything under `system-tests/fixtures/ios-container/ElectrodeContainer/Libraries` and add `system-tests/fixtures/ios-container/ElectrodeContainer/Libraries/` to the `.gitignore` as part of this PR.
There are some changes that are needed for system tests to properly exclude this `Libraries` directory from comparison during system tests as it will still be generated part of the tests. I have opened https://github.com/electrode-io/electrode-native/pull/1308 to handle this.

**Comment by belemaire** [comment]
@friederbluemle 
One sec, will update #1308 to get rid of `system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/Libraries` as the change was only made for `system-tests/fixtures/ios-container/ElectrodeContainer/Libraries`

**Comment by belemaire** [comment]
@friederbluemle 
Please also `git rm` path `system-tests/fixtures/api-impl-native/ReactNativeErnmovieApiImplNative/ios/ElectrodeApiImpl/Libraries` as part of this PR and add to `.gitignore` in addition to the `system-tests/fixtures/ios-container/ElectrodeContainer/Libraries`
Will lighten the repo :)

**Comment by belemaire** [comment]
Ok, just updated #1308 to exclude the `Libraries` directory of native implementation fixture.

**Comment by friederbluemle** [comment]
Awesome! :+1: Which PR should be merged first?

**Comment by belemaire** [comment]
@friederbluemle 
Ideally mine should be merged first otherwise if the directories are not there anymore (through your PR) then system tests will still generate the `Libraries` and try to compare with a fixture that does not have this directory (because your PR will remove these directories from the repo) and will fail.

**Comment by friederbluemle** [comment]
Cool! I'll also include a couple of other minor consolidations for `.gitignore` at the same time 👍

**Pull request merged**
