### PR TITLE
Add cauldron native-app-descriptior example

### PR DESCRIPTION
**Pull request by clairewli**
Add native-app-descriptior example for Cauldron doc

### CODE REVIEW

**Comment by clairewli** [comment]
@belemaire not sure if that makes sense to you. Just feel an example will be easier to user if they are following this part of the docs to setup cauldron

**Comment by belemaire** [comment]
@clairewli Yes makes sense. Could you please just reword your commit message ? when writing release notes I am looking at all commits, makes it easier when the commit message is clear. 
`Add cauldron` is a very generic commit message, looks like your commit adds the Cauldron to platform ;)

Maybe `Add cauldron add nativeapp example to documentation` instead.

From your branch, `git rebase -i HEAD~1` and then replace `pick` by `r` (or `reword`), save and when vim is launched again just edit your commit message, save then force push to your `docs-cauldron-example` branch.

**Comment by clairewli** [comment]
@belemaire  not sure how it gets messed up :(  It's fixed now.

**Comment by belemaire** [comment]
:+1: Thank you, merging now :)

**Pull request merged**
