### PR TITLE
Fix emulator config storage

### PR DESCRIPTION
**Pull request by deepueg**
fixes https://github.com/electrode-io/electrode-native/issues/362

### CODE REVIEW

**Comment by krunalsshah** [comment]
Fixes a specific issue? #363? It tags the PR itself?

**Comment by deepueg** [comment]
Sorry, autofill issue. updated .

**Comment by krunalsshah** [comment]
What is the benefit of hosting the emulatorConfig per platform? By having it contained in the `emulatorConfig`, and then having `android` and `ios` as inner object we are already implying it's specific to the platform.

**Comment by krunalsshah** [comment]
I believe the tests will fail, as emulatorConfig is consumed at multiple places in the platform code.

**Pull request closed without merging**
