### PR TITLE
Fix create-miniapp template processing (TypeScript)

### PR DESCRIPTION
**Pull request by friederbluemle**
A few closely related fixes and updates here. High level summary:

### React Native CLI

With this PR merged, we will be using `npx --ignore-existing react-native` to invoke the `init` command of the React Native CLI when RN >=0.60. Previously, we would just run `react-native`, which either resolves in a globally installed old CLI, or the `react-native-cli` package dependency (old as well). It is not recommended to use the old CLI with RN 0.60+. One problem that it puts non-reproducible and potentially incompatible devDependencies in the resulting `package.json`. The other, more visible problem is related to broken template processing (see below).

### TypeScript template

`create-miniapp`'s template processing that has been broken for quite a while, and as a side effect of the updated RN CLI, this is now fixed. The problem was the old cli's ability to correctly process a template with RN 0.60+ was completely broken. Now that we're using the new way to call RN using `npx` (with a couple of tweaks), template processing works again!

### `--language` deprecation

The `--language` option was never really compatible with the `--template` option in the first place (an unlikely scenario tbh), but now it has been cleaned up and streamlined. The functionality has been fully replaced by the more precise and flexible `--template` option.
We now follow the behavior of React Native (i.e. _no_ additional prompt, and _no_ custom template by default). If needed, a template _can_ be supplied on command line. For now, existing options should continue to work as before, and a deprecation notice will be printed to the console. We can remove them in a future release.

I tested this with RN 0.60 and RN 0.62 (pre-merge, @belemaire's current `cocoapods` branch), both work with the default template and [react-native-template-typescript](https://github.com/react-native-community/react-native-template-typescript).

For example, if the TypeScript template should be used, this is the command with the current version of ERN (i.e. RN 0.60):

```sh
ern create-miniapp --template react-native-template-typescript@6.2.0 app01
```

For RN 0.62, **no** version number after the template is needed. The version compatibility is listed on their website.

Related: #1254 #1443

### CODE REVIEW

**Comment by belemaire** [comment]
Look like CI checks are failing because this PR uses `deprecateOption` of `yargs` but it seems like it doesn't exist in the version used. My guess is that this PR is dependent on this one https://github.com/electrode-io/electrode-native/pull/1562 which bump `yargs` version.
If that's the case could you merge https://github.com/electrode-io/electrode-native/pull/1562 asap and rebase this one ? I'll review it more in depth later on.

**Comment by friederbluemle** [comment]
Yes, it initially did fail with `deprecateOption` (which is why I temporarily included the commit to update yargs here). The CI failure was then again because of the unit test timeout. Anyway, now that #1562 is merged, I can rebase now.

**Comment by friederbluemle** [comment]
Ooh.. Hmmm.. So it does fail with a different error on Azure and GH Actions. Unit test timeout on GH Actions and this error on Azure:

```
$ ern-typescript
running tsc with [ '--project',
  '/Users/runner/runners/2.166.3/work/1/s/ern-local-cli/tsconfig.release.json' ]
src/commands/create-miniapp.ts(31,6): error TS2339: Property 'deprecateOption' does not exist on type 'Argv<{ language: string | undefined; }>'.
```

I know the `deprecateOption` is pretty new and not yet part of the type definitions. I am using it locally, and while the IDE does put a squiggly line under it, the code works fine. Does it mean we cannot use it yet @belemaire? Or need a manual type definition?

**Comment by belemaire** [comment]
Yeah the code will work, but type checking will fail :(

Indeed it's not yet available in [yargs type definitions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/yargs/index.d.ts)
Should be added soon I guess, it's a popular package so types should be well maintained (I could have a take at it and open a PR but it's a complex one, and it'll take time to work on and get merged anyway ...).

Meanwhile two solutions I see.
Either get rid of `deprecateOption` and just log that in the description of the command directly 

```
Language to use for this MiniApp [Deprecated. Use --template]
```

Or do a quick TypeScript module augmentation to add the missing type definition on `yargs` module for this function, by just adding this in the `create-miniapp.ts` source file :

```
declare module 'yargs' {
  interface Argv<T = {}> {
    deprecateOption<K extends string>(key: K, message: string): Argv<T>
  }
}
```

And we can then remove it later whenever official type definition is updated to add this function.

**Comment by belemaire** [comment]
@friederbluemle 
Best way for now is to use the `deprecated` property directly rather than chaining function:

```js
.option('language', {
  choices: ['JavaScript', 'TypeScript', undefined],
  deprecated: 'use --template directly',
  describe: 'Language to use for this MiniApp',
  type: 'string',
})
```

This won't complain / won't fail the build and achieve the same.

**Comment by friederbluemle** [comment]
Awesome, thanks a lot for the additional information!!
I went with just putting it in as a separate field (rather than method call). :+1:

**Comment by belemaire** [comment]
Is `npx` required here to make the typescript template properly work or are they unrelated ? From your comment it would sound like its needed.

There are unfortunately some catches with `npx react-native`.

-  It's only supported [starting from react native 0.60.0](https://github.com/react-native-community/cli#using-npx-recommended). 
For example `npx react-native init foo --version 0.59.0` will fail, while it will succeed with any version >= 0.60.0. 
So the problem here is that if we do it this way, we have to mention that ern 0.41.0 will only support react native >= 0.60.0. Because when we run `ern create-miniapp` it checks in the team override manifest for version of react native to use (on which all miniapps are aligned) and some teams might still be on versions of react native < 0.60.0, which will then fail the command (as it runs `react-native init` under the hood). 
I think this could be addressed by only using `npx react-native init` in our `init` function, if the react native versions is >= 0.60.0, otherwise fallback on global `react-native`. The problem should only be limited to `init` because for other commands `npx react-native` will just use the locally installed `react-native` from `node_modules/.bin` (see my next point).
But if not using `npx` (for react native < 0.60.0), I guess typescript template will still fail. But I think we should still keep the `--template` option as it might be used for other templates. The quirks with this option will be the same as if directly using the react native cli and not ern.

- `npx` will only download react-native and use the latest CLI if `react-native` is not in global path. That's the behavior of `npx`, it will first look it a `react-native` binary is on global path, if so it will use it, otherwise it will look in current local path `node_modules/.bin` and if so it will use it, otherwise it will install it on the fly.
What this means is that even if we run `npx react-native init` for version of RN > 0.60.0, it will still use the old CLI that was installed globally :( And will result in same problems with typescript templates I guess. And almost all of current RN developers have it installed globally.
So we will have the kind of 'it's working on my machine but not yours' issues :(
One way to bypass that would be to use the `--ignore-existing` option of `npx` :
```
--ignore-existing      Ignores existing binaries in $PATH, or in the local
                         project. This forces npx to do a temporary install and
                         use the latest version.
```
But the problem with that, is that it will be costly to do that when `react-native` is available locally (for example run-android, start ... all these commands but init will use the local `node_modules/.bin/react-native` when being run with `npx`, so won't need another install).
But I think we could just use this option in `init` and in all other commands just use `npx react-native` without this flag as the binary will be present locally.

So yeah, to put it in a nutshell, maybe a solution here addressing both points is just to :
- Use `npx` in `init` iff react native version >= 0.60.0, and use it with `--ignore-existing` flag.
- Use `npx` in all other functions, without version check, but use it without `--ignore-existing` flag.

You can have a closer look at it to validate :)

**Comment by friederbluemle** [comment]
Thanks @belemaire for the detailed review! 👌 🙇

What you said makes sense, especially with `--ignore-existing` - I actually ran into this same exact problem a while ago, and should have remembered!

I guess if we absolutely have to keep a new "major" version of ERN compatible with old versions of RN (something that even RN's _own_ CLI is _not_ doing!), then we can try the approach of selectively using npx and a locally installed older cli depending on the use case. Btw, personally I think it's great how ERN is attempting to preserve backwards compatibility as much as possible. Though as we all know, looking around the whole ecosystem, breaking compatibility is something that's done in many projects every day, without strong reasons :/ And no, being on a fake "`0.x`" major version range is not a valid excuse (looking at react-native here).

One thing we do need in order to keep this project relevant is to find the right balance of proper engineering and blending in+keeping **up-to-date** with the 100s/1000s of dependencies we have to deal with.

**Comment by belemaire** [comment]
@friederbluemle Ran a few manual tests with this one, all good :+1:
Just one minor thing, could you remove the default value for `language` that is set [here](https://github.com/electrode-io/electrode-native/blob/a494ad49c7186b04816ca90c6894144f6b5f577f/ern-core/src/MiniApp.ts#L102)
Otherwise we run into warning message `⚠ Both language and template are set. Ignoring language.` when running `ern create-miniapp` even without providing the `language` option to the command ;) A bit bothering.
Once addressed, please merge this PR asap :)
Thanks !

**Comment by friederbluemle** [comment]
Found another scenarios that failed (already updated the code): Creating a miniapp using RN < 0.60 and `--language TypeScript` - The template needs a different name depending on the version 🤦

**Comment by belemaire** [comment]
That's OK, starting with 0.41.0 the option is now deprecated so it's assumed it's not maintained anymore and can break in some context 🤣
Anyway, I think we could safely remove this option in 0.42.0 now that its been deprecated. Because this is not a command that is used on a frequent basis, I really doubt some users have scripted / automated it, so a disappearing option won't break a lot -if any- usages.
Please merge whenever you can, waiting on this one for 0.41.0 release 😄

**Pull request merged**
