### PR TITLE
Update typescript to 4.2.4

### PR DESCRIPTION
**Pull request by friederbluemle**
Major TypeScript update to version 4.1.3

The new version requires `<void>` type arguments for promises that resolve with nothing, otherwise it would fail with a compile error. I added the type arguments as a separate commit.

### CODE REVIEW

**Comment by friederbluemle** [comment]
Tests are failing, needs some more work.

**Comment by belemaire** [comment]
@friederbluemle whenever you have a sec, could you please allow edit by maintainers for this branch ? looks like it's not enabled as I get permission denied when trying to push to the branch _(or something else is going on)_
Thanks to your prep-work done in this PR, I have bumped TypeScript to latest (4.2.4) and fixed all resulting linting and test issues. Would just like to add this commit on top of your branch and go proceed with merge.

**Comment by friederbluemle** [comment]
@belemaire - Sure! You should have access to the branch now! I've rebased it, please add the necessary fixes.. Sorry for not getting to it earlier.

**Comment by belemaire** [comment]
Thanks @friederbluemle !
No worries :) 
Additional commit ac147ca bump to TypeScript 4.2.4. It also bumps tslint to latest (6.1.3), along with all testing related framework dependencies to their latest. 
Updates the code base accordingly to fix new TSLint reported errors and to fix broken tests mostly due to a change in the way TypeScript transpile some export statements.

**Review by belemaire — APPROVED** [review]

**Pull request merged**
